import "./globals.css";

// 抑制antd的警告
if (typeof window !== 'undefined') {
  // 重写console.warn来过滤掉特定的警告
  const originalWarn = console.warn;
  console.warn = function(...args) {
    // 过滤掉antd的Tooltip警告
    if (args[0] && typeof args[0] === 'string' && 
        (args[0].includes('[antd: Tooltip] `overlayClassName` is deprecated') || 
         args[0].includes('[antd: Tooltip] `overlayStyle` is deprecated'))) {
      return;
    }
    originalWarn.apply(console, args);
  };
}

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
import StyleRegistry from "@/layout/StyleRegistry";
import AppTheme from "@/layout/AppTheme";

export const generateViewport = async () => {
  return {
    initialScale: 1,
    minimumScale: 1,
    themeColor: [
      { color: "#f8f8f8", media: "(prefers-color-scheme: light)" },
      { color: "#000", media: "(prefers-color-scheme: dark)" }
    ],
    viewportFit: "cover",
  }
}

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <body suppressHydrationWarning>
      <StyleRegistry>
          <AppTheme>
              {children}
          </AppTheme>
      </StyleRegistry>
      </body>
      </html>
  );
}
export { generateMetadata } from "./metadata"
   