import "./globals.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export { generateMetadata } from "./metadata"
import StyleRegistry from "@/layout/StyleRegistry";

export const generateViewport = async () => {
  return {
    initialScale: 1,
    minimumScale: 1,
    themeColor: [
      { color: "#f8f8f8", media: "(prefers-color-scheme: light)" },
      { color: "#000", media: "(prefers-color-scheme: dark)" }
    ],
    viewportFit: "cover",
    width: '100%',
    height: '100%'
  }
}

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <body>
      <StyleRegistry>
      {children}
      </StyleRegistry>
      </body>
      </html>
  );
}
   